/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.com.comercializadora.gui;

import java.awt.Color;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import pe.com.comercializadora.controllers.ClienteController;
import pe.com.comercializadora.controllers.TipoDocumentoController;
import pe.com.comercializadora.modelos.Cliente;
import pe.com.comercializadora.modelos.TipoDocumento;

/**
 *
 * @author Andre
 */
public class frmCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmProducto
     */
    TipoDocumentoController tipoDocumentoController = new TipoDocumentoController();
    Cliente cliente = new Cliente();

    public frmCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbx_list();
        mostrar("");
        limpiar();

    }

    void cbx_list() {
        for (int i = 0; i < tipoDocumentoController.list().size(); i++) {
            cbx_tipo_documento.addItem(tipoDocumentoController.list().get(i).getNombre());
            //System.out.println(tipo)
        }

    }

    void ocultar_columnas() {
        tabla_cliente.getColumnModel().getColumn(0).setMaxWidth(0);
        tabla_cliente.getColumnModel().getColumn(0).setMinWidth(0);
        tabla_cliente.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabla_cliente.getColumnModel().getColumn(1).setMaxWidth(0);
        tabla_cliente.getColumnModel().getColumn(1).setMinWidth(0);
        tabla_cliente.getColumnModel().getColumn(1).setPreferredWidth(0);
    }

    void limpiar() {
        txt_celular.setText("");
        txt_numero_documento.setText("");
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_email.setText("");
        txt_celular.setText("");
        cbx_tipo_documento.setSelectedIndex(0);
        btn_eliminar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        btn_registrar.setText("Registrar");

    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            ClienteController controller = new ClienteController();
            modelo = controller.mostrar(buscar);
            tabla_cliente.setModel(modelo);
            ocultar_columnas();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_numero_documento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cbx_tipo_documento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btn_cancelar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_celular = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_cliente = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txt_buscar_marca = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 105, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/com/comercializadora/resources/clientes.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 105, 212));
        jLabel3.setText("Tipo Documento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(34, 105, 212));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 380, 10));

        txt_numero_documento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_numero_documento.setForeground(new java.awt.Color(102, 102, 102));
        txt_numero_documento.setBorder(null);
        jPanel2.add(txt_numero_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 370, 30));

        jSeparator3.setForeground(new java.awt.Color(34, 105, 212));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 380, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 105, 212));
        jLabel4.setText("Numero Documento:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(34, 105, 212));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 380, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 105, 212));
        jLabel5.setText("Nombre:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(102, 102, 102));
        txt_email.setBorder(null);
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 370, 30));

        jSeparator5.setForeground(new java.awt.Color(34, 105, 212));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 380, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 105, 212));
        jLabel6.setText("Dirección:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        cbx_tipo_documento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbx_tipo_documento.setForeground(new java.awt.Color(102, 102, 102));
        cbx_tipo_documento.setSelectedIndex(-1);
        cbx_tipo_documento.setBorder(null);
        jPanel2.add(cbx_tipo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 380, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 105, 212));
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(34, 105, 212));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 380, 10));

        btn_cancelar.setBackground(new java.awt.Color(13, 55, 212));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 130, -1));

        btn_registrar.setBackground(new java.awt.Color(13, 55, 212));
        btn_registrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 130, -1));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(102, 102, 102));
        txt_nombre.setBorder(null);
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 370, 30));

        txt_direccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(102, 102, 102));
        txt_direccion.setBorder(null);
        jPanel2.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 370, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 105, 212));
        jLabel8.setText("Celular:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        txt_celular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_celular.setForeground(new java.awt.Color(102, 102, 102));
        txt_celular.setBorder(null);
        jPanel2.add(txt_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 370, 30));

        jSeparator7.setForeground(new java.awt.Color(34, 105, 212));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 380, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Clientes"));

        tabla_cliente = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
    );
    tabla_cliente.setFocusable(false);
    tabla_cliente.getTableHeader().setReorderingAllowed(false);
    tabla_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tabla_clienteMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tabla_cliente);

    jLabel9.setText("Buscar:");

    jSeparator8.setForeground(new java.awt.Color(34, 105, 212));

    txt_buscar_marca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    txt_buscar_marca.setForeground(new java.awt.Color(102, 102, 102));
    txt_buscar_marca.setBorder(null);
    txt_buscar_marca.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txt_buscar_marcaKeyPressed(evt);
        }
    });

    btn_buscar.setBackground(new java.awt.Color(13, 55, 212));
    btn_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
    btn_buscar.setText("buscar");
    btn_buscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_buscarActionPerformed(evt);
        }
    });

    btn_salir.setBackground(new java.awt.Color(13, 55, 212));
    btn_salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btn_salir.setForeground(new java.awt.Color(255, 255, 255));
    btn_salir.setText("salir");
    btn_salir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_salirActionPerformed(evt);
        }
    });

    btn_eliminar.setBackground(new java.awt.Color(13, 55, 212));
    btn_eliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
    btn_eliminar.setText("eliminar");
    btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_eliminarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(btn_eliminar)
                            .addGap(29, 29, 29)
                            .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_buscar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap())))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_buscar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9))
            .addGap(0, 0, 0)
            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_salir)
                .addComponent(btn_eliminar)
                .addComponent(btn_buscar))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
            .addContainerGap())
    );

    jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 570, 500));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void tabla_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_clienteMouseClicked
        // TODO add your handling code here:
        //tabla_categoria.getColumnModel().getColumn(0).setMaxWidth(0);
        //tabla_categoria.getColumnModel().getColumn(0).setMinWidth(0);
        if (evt.getClickCount() == 2) {
            btn_cancelar.setEnabled(true);
            int idCli = 0;
            int idTipDoc = 0;
            String numero_documento = "";
            String nombre = "";
            String direccion = "";
            String celular = "";
            String email = "";
            String estado_registro = "";
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 0) != null) {
                idCli = Integer.parseInt(tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 0).toString());

            }
            
            
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 1) != null) {
                idTipDoc = Integer.parseInt(tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 1).toString());
            }
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 3) != null) {
                numero_documento = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 3).toString();
            }
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 4) != null) {
                nombre = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 4).toString();
            }
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 5) != null) {
                direccion = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 5).toString();
            }
            
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 6) != null) {
                celular = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 6).toString();
            }
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 7) != null) {
                email = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 7).toString();
            }
            if (tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 8) != null) {
                estado_registro = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 8).toString();
            }

            cliente.setId(idCli);
            cliente.setTipo_documento(new TipoDocumento(idTipDoc, "", ""));
            cliente.setNumero_documento(numero_documento);
            cliente.setNombre(nombre);
            cliente.setEmail(email);
            cliente.setCelular(celular);
            int index_tipdoc = tipoDocumentoController.list_compareID(tipoDocumentoController.list(), idTipDoc);
            cbx_tipo_documento.setSelectedIndex(index_tipdoc);
            txt_numero_documento.setText(numero_documento);
            txt_nombre.setText(nombre);
            txt_direccion.setText(direccion);
            txt_email.setText(email);
            txt_celular.setText(celular);
            btn_registrar.setText("Editar");
            btn_eliminar.setEnabled(true);
            if (estado_registro.equals("I")) {
                btn_eliminar.setText("Activar");
            }
            if (estado_registro.equals("A")) {
                btn_eliminar.setText("Desactivar");
            }
        }
    }//GEN-LAST:event_tabla_clienteMouseClicked

    private void txt_buscar_marcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_marcaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_buscar_marcaKeyPressed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        mostrar(txt_buscar_marca.getText());

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        ClienteController controller = new ClienteController();
        int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Esta Seguro de "+btn_eliminar.getText()+" este item","Confirmar",2);
        if(confirmacion==0){
            if(btn_eliminar.getText().equals("Desactivar")){

                controller.desactivar(cliente);
            }
            if(btn_eliminar.getText().equals("Activar")){
                controller.activar(cliente);
            }
        }
        else{
            return;
        }
        mostrar("");
        limpiar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
        int index_tipo_documento = tipoDocumentoController.list().get(cbx_tipo_documento.getSelectedIndex()).getId();

        String nombre = txt_nombre.getText();
        String numero_doc = txt_numero_documento.getText();
        String direccion = txt_direccion.getText();
        String email = txt_email.getText();
        String celular = txt_celular.getText();
        ClienteController clienteController = new ClienteController();

        if (numero_doc.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Obligario ingrear un numero documento");
            txt_nombre.requestFocus();
            return;
        }
        if (nombre.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Obligario ingrear un nombre y apellido");
            txt_nombre.requestFocus();
            return;
        }
        if (btn_registrar.getText().equals("Registrar")) {
            cliente.setNombre(nombre);
            cliente.setNumero_documento(numero_doc);
            cliente.setDireccion(direccion);
            cliente.setCelular(celular);
            cliente.setEmail(email);
            cliente.setTipo_documento(new TipoDocumento(index_tipo_documento, "", ""));
            clienteController.insertar(cliente);
            JOptionPane.showMessageDialog(rootPane, "Colaborador Registrado con EXITO");

        }
        if (btn_registrar.getText().equals("Editar")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Esta Seguro de actualizar este item", "Confirmar", 2);
            if (confirmacion == 0) {
                cliente.setNombre(nombre);
                cliente.setNumero_documento(numero_doc);
                cliente.setDireccion(direccion);
                cliente.setCelular(celular);
                cliente.setEmail(email);

                cliente.setTipo_documento(new TipoDocumento(index_tipo_documento, "", ""));
                clienteController.editar(cliente);
            } else {
                return;
            }
        }

        limpiar();
        mostrar("");

    }//GEN-LAST:event_btn_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbx_tipo_documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable tabla_cliente;
    private javax.swing.JTextField txt_buscar_marca;
    private javax.swing.JTextField txt_celular;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numero_documento;
    // End of variables declaration//GEN-END:variables
}
